artisan arabic
Syrian-Open-Source/arabic-laravel-docs pull request #69
Opened 2022-03-10 12:18 UTC by lumi-hussien

2022-03-15 19:53 UTC, karam-mustafa commented
@lumi-hussien  Hello lumi
have you finished this file ?

2022-03-16 04:53 UTC, lumi-hussien commented
Hi karam
Yes, I have finished

2022-03-16 18:20 UTC, karam-mustafa requested changes

2022-03-16 18:20 UTC, karam-mustafa commented on artisan.md
> +#وحدة تحكم الحرفي الماهر
please keep the English phrase

2022-03-16 18:20 UTC, karam-mustafa commented on artisan.md
> -    - [Tinker (REPL)](#tinker)
Kepp the valid links, in this line and all the links below

2022-03-16 18:20 UTC, karam-mustafa commented on artisan.md
> +التنكر مضمن افتراضيا بتطبيقات اللارافل لكن يمكنك استخدام Composer لتنصيبه في حال حذفه من التطبيق
keep "tinker" instead of "تنكر"

2022-03-16 18:20 UTC, karam-mustafa commented on artisan.md
> +التنكر يسمح لك التفاعل مع تطبيق اللارافل في واجهة الأوامر و المودلات و الاعمال و الاحداث
Replace all works "tinker" with "تنكر", because it is the name of the package, not the term for the technical

2022-03-17 08:36 UTC, lumi-hussien commented
ok

2022-03-17 08:40 UTC, closed without merging