Arabic facades
Syrian-Open-Source/arabic-laravel-docs pull request #70
Opened 2022-03-11 23:58 UTC by Mahmoud217TR

I didn't want to translate the word "stub" to "بذرة" so I left it stub is that ok or is there any other translation suggestions?
also I translated "Real-Time" to "فوري" instead of "أثناء الاستخدام".

2022-03-13 17:36 UTC, karam-mustafa commented
@Mahmoud217TR Hello, 
I suggest translating "stub" into: "النموذج القابل للاستبدال"
and Real-time info: "الوقت الحالي" or "وقت النتفيذ" 
If you had finished, please add the new words into dictionary

2022-03-13 19:51 UTC, karam-mustafa requested changes

2022-03-13 19:51 UTC, karam-mustafa commented on facades.md
> +تعمل واجهات لارافيل Facades بصفتها وكيل ستاتيكي ("static proxies") للصفوف الأساسية في حاوي الخدمة، حيث توفر ميزة الصياغة المعبرة والموجزة مع الحفاظ على قابلية الاختبار ومرونة أكبر من الطرق الستاتيكية
we will translate class as "كائن"

2022-03-13 19:51 UTC, karam-mustafa commented on facades.md
> +كل واجهات لارافيل Facades معرفة ضمن فضاء الأسماء `Illuminate\Support\Facades`. أي أنه يمكننا وبسهولة الوصول لـ Facades بالأسلوب التالي:
convert "فضاء" to "نطاق" and add it to the dictionary please

2022-03-13 19:51 UTC, karam-mustafa commented on facades.md
> +على سبيل المثال، بدلاً من استخدام الـ  Facade التالي `Illuminate\Support\Facades\Response` لانشاء رد من النوع JSON يمكنك ببساطة استخدام التابع المساعد `response`. ولأن التوابع المساعدة متوفرة على نطا
I think it is better to add (response) after "رد"

2022-03-13 19:51 UTC, karam-mustafa commented on facades.md
> +الصف الأساسي `Facade` يستخدم الطريقة السحرية (magic-method) `()callStatic__` لتحويل الاستدعاءات من واجهة Facade لكائن يتم الحصول عليه من حاوي الخدمات. في المثال التالي، سيتم استدعاء نظام الذاكرة المؤ
I don't know if the "الطريقة السحرية" is a scientific definition, instead we can say "التوابع الجاهزة" or "تابع الكائن الاساسي"

2022-03-13 19:51 UTC, karam-mustafa commented on facades.md
> +اذا قمنا بإلقاء نظرة على الصف `Illuminate\Support\Facades\Cache` ستجد بأنه لا وجود للطريقة الستاتيكية `get`:
the word "ستاتيك" is accepted, please add it into dictionary

2022-03-14 11:42 UTC, Mahmoud217TR commented
Consider it done, no worries.

2022-03-14 11:44 UTC, Mahmoud217TR commented on facades.md
> +تعمل واجهات لارافيل Facades بصفتها وكيل ستاتيكي ("static proxies") للصفوف الأساسية في حاوي الخدمة، حيث توفر ميزة الصياغة المعبرة والموجزة مع الحفاظ على قابلية الاختبار ومرونة أكبر من الطرق الستاتيكية
you mean instead of "الصفوف الأساسية" we should use "كائنات أساسية" ?

2022-03-14 11:59 UTC, Mahmoud217TR commented on facades.md
> +تعمل واجهات لارافيل Facades بصفتها وكيل ستاتيكي ("static proxies") للصفوف الأساسية في حاوي الخدمة، حيث توفر ميزة الصياغة المعبرة والموجزة مع الحفاظ على قابلية الاختبار ومرونة أكبر من الطرق الستاتيكية
or should I replace all "صفوف" to "كائنات"

2022-03-14 12:27 UTC, Mahmoud217TR commented on facades.md
> +تعمل واجهات لارافيل Facades بصفتها وكيل ستاتيكي ("static proxies") للصفوف الأساسية في حاوي الخدمة، حيث توفر ميزة الصياغة المعبرة والموجزة مع الحفاظ على قابلية الاختبار ومرونة أكبر من الطرق الستاتيكية
other modifications are ready, waiting for confirmations about classes

2022-03-14 13:39 UTC, karam-mustafa commented on facades.md
> +تعمل واجهات لارافيل Facades بصفتها وكيل ستاتيكي ("static proxies") للصفوف الأساسية في حاوي الخدمة، حيث توفر ميزة الصياغة المعبرة والموجزة مع الحفاظ على قابلية الاختبار ومرونة أكبر من الطرق الستاتيكية
yes replace all words that contains "صف او صفوف" into "كائن او كائنات"

2022-03-14 16:23 UTC, Mahmoud217TR commented on facades.md
> +تعمل واجهات لارافيل Facades بصفتها وكيل ستاتيكي ("static proxies") للصفوف الأساسية في حاوي الخدمة، حيث توفر ميزة الصياغة المعبرة والموجزة مع الحفاظ على قابلية الاختبار ومرونة أكبر من الطرق الستاتيكية
Ok I'm on it.

2022-03-14 16:40 UTC, Mahmoud217TR commented
I guess this is done.
Ready for any other suggestions.

2022-03-14 23:36 UTC, merged